# Generated by Django 5.2.14 on 2026-06-11 05:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinforcementTypes',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'reinforcement_types',
            },
        ),
        migrations.CreateModel(
            name='TrainingLevels',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'training_levels',
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('estimated_duration', models.IntegerField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.traininglevels')),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlans',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='training.traininglevels')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dogs')),
            ],
            options={
                'db_table': 'training_plans',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlanExercises',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('order_number', models.IntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercises')),
                ('reinforcement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.reinforcementtypes')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingplans')),
            ],
            options={
                'db_table': 'training_plan_exercises',
            },
        ),
    ]
