# Generated by Django 5.2.14 on 2026-06-19 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplans',
            name='current_level',
            field=models.ForeignKey(blank=True, db_column='current_level', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='training.traininglevels'),
        ),
    ]
