# Generated by Django 5.2.14 on 2026-06-11 05:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiRecommendations',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dogs')),
                ('previous_strategy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_recommendations', to='training.reinforcementtypes')),
                ('recommended_strategy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommended_recommendations', to='training.reinforcementtypes')),
            ],
            options={
                'db_table': 'ai_recommendations',
            },
        ),
    ]
